version: '3'
services:
  app:
    build: .
    ports:
      - "3010:3000"
    environment:
      - PORT=3000
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./nodemon.json:/app/nodemon.json
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "3010:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
