name: express-app

services:
  app:
    image: vaibhavgabani/express-app:latest
    container_name: express-app
    ports:
      - "3010:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - HOST=0.0.0.0
      - RUNNING_IN_DOCKER=true
      - PORT_MAPPING_OK=true
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./nodemon.json:/app/nodemon.json
    restart: always
    # Adding labels for better documentation
    labels:
      - "com.example.description=Express API"
      - "com.example.port.mapping=3010:3000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
